[package]
name = "memflowup"
version = "0.1.0-beta1"
authors = ["Aurimas Blažulionis <0x60@pm.me>", "ko1N <ko1N1337@gmail.com>"]
edition = "2018"
description = "setup tool for the memflow physical memory introspection framework"
documentation = "https://docs.rs/memflowup"
readme = "README.md"
homepage = "https://memflow.github.io"
repository = "https://github.com/memflow/memflowup"
license-file = "LICENSE"
keywords = [ "memflow", "introspection", "memflowup", "memory", "dma" ]
categories = [ "memory-management", "os" ]

[dependencies]
log = { version = "0.4", default-features = false }
simple_logger = "1.16"
rhai = "0.19"
clap = "2"
serde = "1.0"
serde_json = "1.0"

# scripts
which = "4.0.2"
ureq = "1.2"
pbr = "1.0"
progress-streams = "1.1"
dirs = "3.0"
zip = "0.5"
crc = "2"

