[package]
name = "memflowup"
version = "0.1.0-beta9"
authors = ["Aurimas Blažulionis <0x60@pm.me>", "ko1N <ko1N1337@gmail.com>"]
edition = "2018"
description = "setup tool for the memflow physical memory introspection framework"
documentation = "https://docs.rs/memflowup"
readme = "README.md"
homepage = "https://memflow.github.io"
repository = "https://github.com/memflow/memflowup"
license-file = "LICENSE"
keywords = [ "memflow", "introspection", "memflowup", "memory", "dma" ]
categories = [ "memory-management", "os" ]

[dependencies]
log = "^0.4.14"
simplelog = "^0.11.1"
rhai = "^1.6"
clap = { version = "=3.2.15", features = ["cargo"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# scripts
which = "4.0.2"
ureq = "^2.4"
pbr = "1.0"
progress-streams = "1.1"
dirs = "^4.0"
zip = "^0.6"
crc = "2"
